# Generated by Django 6.0.4 on 2026-04-30 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('sources', models.ManyToManyField(related_name='groups', to='collector.source')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('articles', models.ManyToManyField(related_name='events', to='collector.article')),
            ],
        ),
        migrations.CreateModel(
            name='SimilarityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('source_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_a', to='collector.source')),
                ('source_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_b', to='collector.source')),
            ],
            options={
                'unique_together': {('source_a', 'source_b')},
            },
        ),
    ]
