# Generated by Django 6.0.5 on 2026-05-14 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('collector', '0002_article_embedding_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='article_count_snapshot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='cosine_threshold',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='similarityrecord',
            name='cosine_similarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='similarityrecord',
            name='euclidean_distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='similarityrecord',
            name='manhattan_distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='similarityrecord',
            name='similarity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='SourceNetworkMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_centrality', models.FloatField(default=0.0)),
                ('betweenness_centrality', models.FloatField(default=0.0)),
                ('connections_count', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_metrics', to='collector.source')),
            ],
        ),
    ]
