# Generated by Django 6.0.4 on 2026-04-30 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('rss_url', models.URLField(unique=True)),
                ('category', models.CharField(choices=[('state', 'Державні/надійні'), ('quality', 'Якісні приватні'), ('mass', 'Масові медіа'), ('tabloid', 'Таблоїди/проблемні'), ('regional', 'Регіональні')], default='mass', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('reliability_score', models.FloatField(default=50.0)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='collector.source')),
            ],
        ),
    ]
