# Generated by Django 6.0.5 on 2026-05-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embedding_json',
            field=models.TextField(blank=True, default=''),
        ),
    ]
